version: "3.7"
services:
  apache:
    image: rafael01costa/php:7.3-apache
    container_name: studiosocial
    restart: always
    expose:
      - "443"
    volumes:
      - ./:/var/www/html
    environment:
      - VIRTUAL_HOST=studiosocial.localhost
    networks:
      - network
networks:
  network:
    driver: bridge


